First pass at function to make pretty Fig 3 (and figure for supplement)
USGS-R/regional-hydrologic-forcings-ml pull request #188
Opened 2023-01-23 18:06 UTC by cstillwellusgs

Not finished yet but I do need your feedback. (1) I'm not sure I calculated the error bars quite the same way as you, but they looks similar. (2) General confusion about the raw metrics (full-year) and where the seasons come into play. Let me know if you want to chat this afternoon or later this week and screenshare to make sure I'm computing everything correctly.

2023-01-23 18:29 UTC, cstillwellusgs commented
![cluster_map_barplot_seasonal](https://user-images.githubusercontent.com/43651636/214120546-3a55c405-9687-4359-b5e1-1d896f94b3cf.png)

2023-01-23 20:19 UTC, jds485 commented
I just did a quick check on the quantiles used and it looks like you did the same method as I used (5th and 95th quantiles computed over all gages in the region). For the full-year metrics, seasons are only used for plotting purposes. I think that figure would be a supplement instead of a main figure

2023-01-23 20:26 UTC, jds485 requested changes
I have some initial comments that we can discuss in the meeting

2023-01-23 20:26 UTC, jds485 commented on 3_cluster/src/seasonal_metric_cluster.R
> +    barplot <- ggplot(data = metric_summary) +
Let's fix the ylim to be 0, 1

2023-01-23 20:26 UTC, jds485 commented on 3_cluster.R
> +             plot_map_barplot(gages = p1_feature_vars_g2,
Not sure this edit is right
```suggestion
             plot_map_barplot(gages = p1_feature_vars_g2_sf,
```

2023-01-23 20:26 UTC, jds485 commented on 3_cluster/src/seasonal_metric_cluster.R
> +  #' @param gages dataframe of the gages (rows)
as sf?

2023-01-23 20:26 UTC, jds485 commented on 3_cluster.R
> +                              metric_mat = p2_FDC_metrics,
I think this needs to be seasonal metrics to compute the seasonal barplot. Maybe this is where your confusion was?
```suggestion
                              metric_mat = p2_FDC_metrics_season, 
```

2023-01-30 20:51 UTC, cstillwellusgs commented
![cluster_map_barplot_seasonal](https://user-images.githubusercontent.com/43651636/215592050-6b3afb07-47af-42a7-80b7-f9139cbf812b.png)

2023-01-30 20:54 UTC, cstillwellusgs commented
![cluster_map_barplot_fullyear](https://user-images.githubusercontent.com/43651636/215592629-91e1767f-c816-484c-9590-573164c1bea9.png)

2023-01-30 21:50 UTC, jds485 approved these changes
Looks good!

2023-01-31 13:45 UTC, merged