Logs to track changes to dataRetrieval requests
USGS-R/regional-hydrologic-forcings-ml pull request #46
Opened 2022-01-29 17:30 UTC by cstillwellusgs

I used Lauren's example code from the drb-inland-salinity repo. I might still be missing something... as it is now, the log files will overwrite previous logs. Lauren mentioned something about using diff to compare old and new logs, but I'm not sure if we want to keep a running log (do not overwrite old logs) for ease of access down the road?

2022-01-31 13:56 UTC, jds485 commented
This looks good! I think we should track all data pulls from NWIS. Looks like drainage area and flood threshold for this repo

2022-01-31 13:59 UTC, jds485 commented on 1_fetch/src/get_nwis_data.R
> +    summarize(num_days = n(),
Could you add a column for number of provisional or estimated days? Maybe `num_Pe` for the name

2022-01-31 14:00 UTC, jds485 commented on 1_fetch/src/get_nwis_data.R
> +              mean_flow = mean(discharge, na.rm = TRUE),
Similar comment: can you add mean and sd for flows that are not P or e?

2022-01-31 14:13 UTC, jds485 commented on _targets.R
at the top of the `_targets.R` script, add a `dir.create` for `1_fetch/out/logs/`

2022-01-31 14:22 UTC, jds485 commented
> using diff to compare old and new logs

Yes, we'll commit the log files to GitHub. You can commit the log files you generated in this PR. The purpose of the log files is mostly to detect when NWIS data have changed.

> but I'm not sure if we want to keep a running log (do not overwrite old logs) for ease of access down the road?

I think we'd need other log files for tracking the model and input data versions (related to #1). The log files in this PR are tracking raw data changes.

2022-01-31 14:26 UTC, jds485 requested changes
I didn't run this yet, but it looks good! See minor change requests in previous comments. I'll run it after you've addressed those

2022-02-01 16:43 UTC, cstillwellusgs commented
I think I updated the .gitignore file correctly to track the log files....

Addressed all your comments except creating a log for flood threshold, which I think is a function from the EFlowStats package (not dataRetrieval).

2022-02-01 18:37 UTC, jds485 commented on .gitignore
> +*/out/*_pk.csv
You could also use an exception to the rule. Like:
```
*/out/*
!*/out/logs
```

2022-02-01 19:13 UTC, jds485 commented on .gitignore
> +*/out/*_pk.csv
I addressed this in a commit

2022-02-01 19:15 UTC, jds485 approved these changes
Looks good and runs for me. Just one change requested to add the mean and sd for approved data to the log file. You can merge after that. Also note that I added a commit, so you'll need to do a git pull

2022-02-01 21:07 UTC, merged